### ISSUE TITLE
App crashes after WebDav is set

### ISSUE THREAD

**Issue by theautomation** [ONLYOFFICE/documents-app-android#304]
The app crash directly after I fill in the webdav host and login

Phone: Pixel 7
OS: Graphene OS android 14

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023103100:user/release-keys
package: com.onlyoffice.documents:490
process: com.onlyoffice.documents
processUptime: 48182 + 238 ms
installer: com.aurora.store

java.lang.SecurityException: com.onlyoffice.documents: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1801)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at app.editors.manager.mvp.presenters.main.DocsWebDavPresenter.onFirstViewAttach(DocsWebDavPresenter.kt:71)
	at moxy.MvpPresenter.attachView(MvpPresenter.java:48)
	at moxy.MvpDelegate.onAttach(MvpDelegate.java:163)
	at moxy.MvpAppCompatFragment.onStart(MvpAppCompatFragment.java:38)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3187)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by michael-efremov** [comment]
Fixed cf4fcc4fbda55e2e28cf128c0c44885b7b134de6
